


export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST"
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE"

export const SINGLE_PRO_ID_REQUEST="SINGLE_PRO_ID_REQUEST";
export const SINGLE_PRO_ID_SUCCESS="SINGLE_PRO_ID_SUCCESS";
export const SINGLE_PRO_ID_FAILURE="SINGLE_PRO_ID_FAILURE";